version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: jobsentinel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobsentinel
      POSTGRES_PASSWORD: jobsentinel
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
